name: Bump Minor Version and Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Type of version bump'
        required: true
        default: 'minor'
        type: choice
        options:
        - minor_and_publish
        - publish

jobs:
  bump-version-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-options: '--depth=0'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine toml

    - name: Bump minor version
      if: github.event.inputs.version_type == 'minor_and_publish'
      run: |
        python -c "import toml; config = toml.load('pyproject.toml'); version = config['project']['version']; major, minor, patch = map(int, version.split('.')); config['project']['version'] = f'{major}.{minor+1}.{patch}'; toml.dump(config, open('pyproject.toml', 'w'))"
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add pyproject.toml
        git commit -m 'Bump minor version'
        git push origin main

    - name: Create Tag
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        git tag v$VERSION
        git push origin v$VERSION

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: python -m twine upload dist/*
