name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run tests with coverage
      id: coverage
      run: |
        pytest

    - name: Run live tests
      if: github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
      env:
        RUN_LIVE_TESTS: 'true'
      run: |
        pytest -m live --reruns 5 --reruns-delay 2 --ignore=tests/test_server.py
